# Generated by Django 4.2.2 on 2023-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(default='/media/blank_profile.png', max_length=500),
        ),
    ]
